function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 30-Oct-2017 13:44:33

% Create figure
figure1 = figure('NumberTitle','off','Name','sin(x)');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','sin','Marker','hexagram','LineWidth',4,...
    'LineStyle',':',...
    'Color',[0 0 1]);

% Create xlabel
xlabel('x');

% Create title
title('Sin(x)');

% Create ylabel
ylabel('y');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-4 4]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1 1]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14,'XTick',[-3.14 -1.57 0 1.57 3.14],'XTickLabel',...
    {'-pi','-pi/2','0','pi/2','pi'});
% Create legend
legend(axes1,'show');

